kind: pipeline
type: kubernetes
name: Test

trigger:
  branch:
    - master
  event:
    include:
      - pull_request

steps:
- name: Test application 
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
 commands:
    - lscpu
